/* Jajo: przepisy z jajkiem.
 *
 * Żeby dodać przepis, skopiuj jeden obiekt i zmień jego pola:
 *   id          – krótka nazwa bez polskich znaków i spacji (trafia do adresu, np. przepisy.html#szakszuka)
 *   category    – 'sniadania' | 'obiady' | 'przekaski' | 'desery'
 *   time        – czas pracy w minutach, wait – opcjonalny opis czekania (np. '6 h w lodówce')
 *   difficulty  – 1 łatwe, 2 średnie, 3 wymagające
 *   servings    – na ile porcji są podane ilości, minServings – najmniejsza sensowna liczba porcji,
 *                 step – o ile porcji zmienia się licznik (domyślnie 1)
 *   ingredients – { n: nazwa, q: ilość, u: jednostka, egg: 'whole' | 'yolk' | 'white', opt: true gdy opcjonalny }
 *                 { n: nazwa, t: 'do smaku' } dla składników bez ilości, { h: 'Nagłówek grupy' }
 *   steps       – tekst albo { t: tekst, timer: sekundy } dla kroków z minutnikiem
 *   photo       – plik w img/przepisy/ i dane autora zdjęcia (licencja wymaga podpisu)
 */
window.JAJO_PRZEPISY = [
  {
    id: 'jajecznica',
    name: 'Jajecznica na maśle',
    category: 'sniadania',
    intro: 'Kremowa, ścięta powoli na małym ogniu. Podstawa, którą warto opanować do perfekcji.',
    time: 10,
    difficulty: 1,
    servings: 2,
    minServings: 1,
    ingredients: [
      { n: 'Jajka', q: 4, u: 'szt.', egg: 'whole' },
      { n: 'Masło', q: 20, u: 'g' },
      { n: 'Szczypiorek', q: 0.5, u: 'pęczek' },
      { n: 'Śmietanka 30%', q: 1, u: 'łyżka', opt: true },
      { n: 'Sól i pieprz', t: 'do smaku' },
    ],
    steps: [
      'Wbij jajka do miski, posól i roztrzep widelcem tylko do połączenia żółtek z białkami. Jeśli chcesz, dodaj śmietankę.',
      'Na patelni roztop masło na małym ogniu. Masło ma się rozpuścić, ale nie zrumienić.',
      'Wlej jajka i odczekaj kilka sekund, aż zaczną ścinać się od spodu.',
      { t: 'Mieszaj powoli szpatułką, zgarniając ścięte jajka od brzegów do środka. Trwa to około 2–3 minut.', timer: 150 },
      'Zdejmij patelnię z ognia, gdy jajecznica jest jeszcze lekko wilgotna. Dojdzie od ciepła patelni. Posyp szczypiorkiem i pieprzem.',
    ],
    tip: 'Posól jajka kwadrans przed smażeniem. Sól zdąży rozpuścić się w białku i jajecznica wyjdzie delikatniejsza.',
    photo: {
      file: 'img/przepisy/jajecznica.jpg', w: 960, h: 1280, focus: '50% 50%',
      author: 'Studio Sarah Lou', license: 'CC BY 2.0', licenseUrl: 'https://creativecommons.org/licenses/by/2.0/',
      source: 'https://commons.wikimedia.org/wiki/File:Scrambled_Eggs_at_Cracker_Barrel.jpg',
    },
  },
  {
    id: 'pasta-jajeczna',
    name: 'Pasta jajeczna ze szczypiorkiem',
    category: 'sniadania',
    intro: 'Klasyk polskiego śniadania. Najlepsza na świeżym pieczywie z rzodkiewką.',
    time: 20,
    difficulty: 1,
    servings: 4,
    minServings: 1,
    ingredients: [
      { n: 'Jajka', q: 4, u: 'szt.', egg: 'whole' },
      { n: 'Majonez', q: 2, u: 'łyżka' },
      { n: 'Jogurt naturalny', q: 1, u: 'łyżka', opt: true },
      { n: 'Musztarda', q: 1, u: 'łyżeczka' },
      { n: 'Szczypiorek', q: 0.5, u: 'pęczek' },
      { n: 'Sól i pieprz', t: 'do smaku' },
      { n: 'Pieczywo', t: 'do podania' },
    ],
    steps: [
      { t: 'Włóż jajka do wrzącej wody i gotuj na twardo przez 9 minut.', timer: 540 },
      'Przełóż jajka do zimnej wody na kilka minut, a potem obierz.',
      'Zetrzyj jajka na tarce o grubych oczkach albo drobno posiekaj nożem.',
      'Wymieszaj z majonezem, jogurtem, musztardą i posiekanym szczypiorkiem. Dopraw solą i pieprzem.',
      'Podawaj od razu na pieczywie albo przechowuj w lodówce do 2 dni.',
    ],
    tip: 'Jajka sprzed kilku dni obierają się łatwiej niż te prosto od kury. Z wiekiem białko traci kwasowość i mniej przywiera do błon pod skorupką.',
    link: { href: 'index.html#minutnik', label: 'Policz czas na twardo dla swoich jajek' },
    photo: {
      file: 'img/przepisy/pasta-jajeczna.jpg', w: 960, h: 720, focus: '50% 78%',
      author: 'T.Tseng', license: 'CC BY 2.0', licenseUrl: 'https://creativecommons.org/licenses/by/2.0/',
      source: 'https://commons.wikimedia.org/wiki/File:Egg_salad,_scallion,_mayo,_dijon.jpg',
    },
  },
  {
    id: 'szakszuka',
    name: 'Szakszuka',
    category: 'sniadania',
    intro: 'Jajka ścięte w pikantnym sosie z pomidorów i papryki, podane prosto z patelni.',
    time: 30,
    difficulty: 1,
    servings: 2,
    minServings: 1,
    ingredients: [
      { n: 'Jajka', q: 4, u: 'szt.', egg: 'whole' },
      { n: 'Pomidory krojone z puszki', q: 400, u: 'g' },
      { n: 'Czerwona papryka', q: 1, u: 'szt.' },
      { n: 'Cebula', q: 1, u: 'szt.' },
      { n: 'Czosnek', q: 2, u: 'ząbek' },
      { n: 'Oliwa', q: 2, u: 'łyżka' },
      { n: 'Kumin mielony', q: 1, u: 'łyżeczka' },
      { n: 'Słodka papryka', q: 1, u: 'łyżeczka' },
      { n: 'Chili', q: 1, u: 'szczypta' },
      { n: 'Feta', q: 50, u: 'g', opt: true },
      { n: 'Natka pietruszki lub kolendra', q: 1, u: 'garść' },
      { n: 'Sól i pieprz', t: 'do smaku' },
    ],
    steps: [
      { t: 'Na oliwie zeszklij pokrojoną cebulę i paprykę. Zajmie to około 5 minut.', timer: 300 },
      'Dodaj posiekany czosnek, kumin, paprykę i chili. Smaż jeszcze minutę, aż przyprawy zapachną.',
      { t: 'Wlej pomidory, dopraw solą i pieprzem. Duś bez przykrycia, aż sos zgęstnieje, około 10 minut.', timer: 600 },
      'Zrób łyżką wgłębienia w sosie i wbij do nich jajka. Posól białka.',
      { t: 'Przykryj patelnię i gotuj na małym ogniu, aż białka się zetną, a żółtka zostaną płynne, około 7 minut.', timer: 420 },
      'Posyp pokruszoną fetą i ziołami. Podawaj prosto z patelni z pieczywem.',
    ],
    tip: 'Wbij każde jajko najpierw do małej miseczki, a potem wlej je do sosu. Łatwiej trafić w dołek i nie rozbić żółtka.',
    photo: {
      file: 'img/przepisy/szakszuka.jpg', w: 960, h: 720, focus: '50% 50%',
      author: 'Calliopejen1', license: 'CC BY-SA 3.0', licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0/',
      source: 'https://commons.wikimedia.org/wiki/File:Shakshuka_by_Calliopejen1.jpg',
    },
  },
  {
    id: 'jajka-po-benedyktynsku',
    name: 'Jajka po benedyktyńsku',
    category: 'sniadania',
    intro: 'Jajka w koszulce na chrupiącej bułce z szynką, polane maślanym sosem holenderskim.',
    time: 30,
    difficulty: 3,
    servings: 2,
    minServings: 1,
    ingredients: [
      { h: 'Jajka w koszulce' },
      { n: 'Jajka', q: 4, u: 'szt.', egg: 'whole' },
      { n: 'Ocet spirytusowy', q: 1, u: 'łyżka' },
      { h: 'Sos holenderski' },
      { n: 'Żółtka', q: 2, u: 'szt.', egg: 'yolk' },
      { n: 'Masło', q: 100, u: 'g' },
      { n: 'Sok z cytryny', q: 1, u: 'łyżka' },
      { n: 'Sól', q: 1, u: 'szczypta' },
      { h: 'Do podania' },
      { n: 'Bułki angielskie (muffiny)', q: 2, u: 'szt.' },
      { n: 'Szynka', q: 4, u: 'plaster' },
      { n: 'Szczypiorek', t: 'do posypania' },
    ],
    steps: [
      'Roztop masło i odstaw, żeby lekko przestygło.',
      { t: 'Żółtka z sokiem z cytryny i łyżką wody ubijaj w misce nad garnkiem z gotującą się wodą, aż zgęstnieją, około 3 minut. Miska nie może dotykać wody.', timer: 180 },
      'Zdejmij miskę z garnka i ciągle ubijając, wlewaj masło cienkim strumieniem. Dopraw solą. Sos odstaw w ciepłe miejsce.',
      'W szerokim garnku zagotuj wodę z octem i zmniejsz ogień tak, żeby woda ledwo się poruszała.',
      { t: 'Wbij jajko do miseczki, zakręć łyżką wir w wodzie i wlej jajko na środek. Gotuj 3 minuty i wyjmij łyżką cedzakową. Tak samo przygotuj resztę jajek.', timer: 180 },
      'Przekrojone bułki opiecz na patelni razem z szynką. Na każdej połówce połóż jajko, polej sosem i posyp szczypiorkiem.',
    ],
    tip: 'Do jajek w koszulce bierz najświeższe jajka. Gęste białko w świeżym jajku trzyma się żółtka i nie rozpływa się w wodzie.',
    link: { href: 'index.html#wnetrze', label: 'Zobacz, czym jest białko gęste' },
    photo: {
      file: 'img/przepisy/jajka-po-benedyktynsku.jpg', w: 960, h: 640, focus: '50% 55%',
      author: 'Mark Miller', license: 'CC BY-SA 4.0', licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
      source: 'https://commons.wikimedia.org/wiki/File:Traditional_Eggs_Benedict.jpg',
    },
  },
  {
    id: 'tortilla',
    name: 'Tortilla hiszpańska',
    category: 'obiady',
    intro: 'Gruby omlet z ziemniakami duszonymi w oliwie. W Hiszpanii je się go na ciepło i na zimno.',
    time: 50,
    difficulty: 2,
    servings: 4,
    minServings: 2,
    ingredients: [
      { n: 'Jajka', q: 6, u: 'szt.', egg: 'whole' },
      { n: 'Ziemniaki', q: 600, u: 'g' },
      { n: 'Cebula', q: 1, u: 'szt.' },
      { n: 'Oliwa', q: 150, u: 'ml' },
      { n: 'Sól', q: 1, u: 'łyżeczka' },
    ],
    steps: [
      'Obierz ziemniaki i pokrój je w cienkie plasterki. Cebulę pokrój w piórka.',
      { t: 'Rozgrzej oliwę na patelni, wrzuć ziemniaki z cebulą i posól. Duś pod przykryciem na małym ogniu, aż zmiękną, około 20 minut. Mają się dusić, a nie rumienić.', timer: 1200 },
      'Odcedź ziemniaki z oliwy. Łyżkę oliwy zostaw na patelni.',
      { t: 'Roztrzep jajka z solą w dużej misce, wmieszaj ciepłe ziemniaki i odstaw na 10 minut.', timer: 600 },
      { t: 'Wylej masę na rozgrzaną patelnię i smaż na średnim ogniu około 5 minut.', timer: 300 },
      { t: 'Przykryj patelnię dużym talerzem, odwróć tortillę na talerz i zsuń ją z powrotem na patelnię. Smaż jeszcze 3 minuty.', timer: 180 },
    ],
    tip: 'Środek tortilli może zostać lekko wilgotny. Właśnie tak podaje się ją w Hiszpanii.',
    photo: {
      file: 'img/przepisy/tortilla.jpg', w: 960, h: 720, focus: '50% 50%',
      author: 'Juan Emilio Prades Bel', license: 'CC BY-SA 4.0', licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
      source: 'https://commons.wikimedia.org/wiki/File:Tortilla_Espa%C3%B1ola.jpg',
    },
  },
  {
    id: 'carbonara',
    name: 'Spaghetti carbonara',
    category: 'obiady',
    intro: 'Prawdziwa carbonara nie ma śmietany. Kremowy sos robią żółtka, ser i woda z makaronu.',
    time: 25,
    difficulty: 2,
    servings: 2,
    minServings: 1,
    ingredients: [
      { n: 'Spaghetti', q: 200, u: 'g' },
      { n: 'Guanciale lub boczek', q: 100, u: 'g' },
      { n: 'Żółtka', q: 3, u: 'szt.', egg: 'yolk' },
      { n: 'Jajko', q: 1, u: 'szt.', egg: 'whole' },
      { n: 'Pecorino romano lub parmezan', q: 50, u: 'g' },
      { n: 'Czarny pieprz', t: 'dużo, świeżo mielony' },
      { n: 'Sól', t: 'do wody' },
    ],
    steps: [
      { t: 'Ugotuj makaron al dente w osolonej wodzie, zwykle około 9 minut.', timer: 540 },
      'W tym czasie pokrój guanciale w paski i podsmaż na suchej patelni, aż tłuszcz się wytopi, a mięso zrobi się chrupiące. Zdejmij patelnię z ognia.',
      'W misce wymieszaj żółtka, jajko, starty ser i dużo pieprzu.',
      'Odcedź makaron i przełóż go na patelnię z guanciale. Zachowaj szklankę wody z gotowania.',
      'Na patelni zdjętej z ognia wlej masę jajeczną i energicznie mieszaj, dolewając po łyżce wody z makaronu, aż powstanie gładki, kremowy sos.',
    ],
    tip: 'Jeśli patelnia będzie zbyt gorąca, jajka zetną się w grudki i zamiast sosu wyjdzie jajecznica z makaronem. Białka, które zostaną, wykorzystaj do pavlovej.',
    photo: {
      file: 'img/przepisy/carbonara.jpg', w: 960, h: 1280, focus: '50% 58%',
      author: 'Andy Li', license: 'CC0', licenseUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
      source: 'https://commons.wikimedia.org/wiki/File:Spaghetti_Carbonara_with_Japanese_Raw_Egg.jpg',
    },
  },
  {
    id: 'zurek',
    name: 'Żurek z jajkiem',
    category: 'obiady',
    intro: 'Kwaśna zupa na zakwasie z białą kiełbasą i połówkami jajek. Wielkanocny klasyk.',
    time: 50,
    difficulty: 1,
    servings: 4,
    minServings: 2,
    ingredients: [
      { n: 'Zakwas na żurek', q: 500, u: 'ml' },
      { n: 'Biała kiełbasa', q: 400, u: 'g' },
      { n: 'Woda', q: 1000, u: 'ml' },
      { n: 'Ziemniaki', q: 400, u: 'g' },
      { n: 'Jajka', q: 4, u: 'szt.', egg: 'whole' },
      { n: 'Czosnek', q: 3, u: 'ząbek' },
      { n: 'Majeranek', q: 1, u: 'łyżka' },
      { n: 'Liście laurowe', q: 2, u: 'szt.' },
      { n: 'Ziele angielskie', q: 3, u: 'szt.' },
      { n: 'Śmietana 18%', q: 100, u: 'ml', opt: true },
      { n: 'Chrzan', q: 1, u: 'łyżka', opt: true },
      { n: 'Sól i pieprz', t: 'do smaku' },
    ],
    steps: [
      { t: 'Zalej kiełbasę wodą, dodaj liście laurowe i ziele angielskie. Gotuj na małym ogniu 20 minut, potem wyjmij kiełbasę i pokrój ją w plastry.', timer: 1200 },
      { t: 'Wrzuć do wywaru ziemniaki pokrojone w kostkę i gotuj do miękkości, około 15 minut.', timer: 900 },
      { t: 'W tym czasie ugotuj jajka na twardo, 9 minut, ostudź i obierz.', timer: 540 },
      'Wstrząśnij butelką z zakwasem i wlej go do zupy. Dodaj przeciśnięty czosnek i majeranek roztarty w palcach. Zagotuj.',
      'Dodaj kiełbasę, śmietanę i chrzan. Dopraw solą i pieprzem. Po dodaniu śmietany już nie gotuj.',
      'Na talerze połóż połówki jajek i zalej je gorącym żurkiem.',
    ],
    tip: 'Żurek z jajkiem to stały punkt wielkanocnego śniadania w wielu polskich domach. Smakuje też w chlebie zamiast talerza.',
    link: { href: 'index.html#minutnik', label: 'Policz czas na twardo dla swoich jajek' },
    photo: {
      file: 'img/przepisy/zurek.jpg', w: 960, h: 960, focus: '50% 50%',
      author: 'Marsilar', license: 'CC BY-SA 4.0', licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
      source: 'https://commons.wikimedia.org/wiki/File:02026_Gut-Healing_Sour_Rye_Soup_with_a_Collagen_Broth.jpg',
    },
  },
  {
    id: 'jajka-faszerowane',
    name: 'Jajka faszerowane',
    category: 'przekaski',
    intro: 'Połówki jajek z kremowym farszem z żółtek. Znikają ze stołu pierwsze.',
    time: 30,
    difficulty: 1,
    servings: 4,
    minServings: 1,
    ingredients: [
      { n: 'Jajka', q: 4, u: 'szt.', egg: 'whole' },
      { n: 'Majonez', q: 2, u: 'łyżka' },
      { n: 'Musztarda', q: 1, u: 'łyżeczka' },
      { n: 'Szczypiorek', q: 0.5, u: 'pęczek' },
      { n: 'Słodka papryka', q: 1, u: 'szczypta' },
      { n: 'Czerwona papryka lub rzodkiewka', t: 'do dekoracji', opt: true },
      { n: 'Sól i pieprz', t: 'do smaku' },
    ],
    steps: [
      { t: 'Włóż jajka do wrzącej wody i gotuj na twardo przez 9 minut.', timer: 540 },
      'Przełóż jajka do zimnej wody na kilka minut, potem obierz.',
      'Przekrój jajka wzdłuż na pół i wyjmij żółtka do miski.',
      'Rozgnieć żółtka widelcem z majonezem i musztardą. Dodaj posiekany szczypiorek, sól i pieprz.',
      'Nałóż farsz łyżeczką albo rękawem cukierniczym do połówek białek. Posyp papryką i udekoruj.',
    ],
    tip: 'Żeby żółtka nie miały szarej obwódki, nie gotuj jajek dłużej niż 10 minut i od razu je schłodź.',
    link: { href: 'index.html#minutnik', label: 'Policz czas na twardo dla swoich jajek' },
    photo: {
      file: 'img/przepisy/jajka-faszerowane.jpg', w: 960, h: 597, focus: '50% 50%',
      author: 'Kurt Bauschardt', license: 'CC BY-SA 2.0', licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.0/',
      source: 'https://commons.wikimedia.org/wiki/File:Deviled_Eggs_(6665206207).jpg',
    },
  },
  {
    id: 'jajka-do-ramenu',
    name: 'Jajka marynowane do ramenu',
    category: 'przekaski',
    intro: 'Japońskie ajitsuke tamago: jajka mollet z żółtkiem jak dżem, przegryzione słodko-słoną marynatą.',
    time: 15,
    wait: '6 h w lodówce',
    difficulty: 1,
    servings: 4,
    minServings: 1,
    ingredients: [
      { n: 'Jajka', q: 4, u: 'szt.', egg: 'whole' },
      { n: 'Sos sojowy', q: 100, u: 'ml' },
      { n: 'Mirin', q: 100, u: 'ml' },
      { n: 'Woda', q: 100, u: 'ml' },
      { n: 'Cukier', q: 1, u: 'łyżeczka', opt: true },
      { n: 'Lód', t: 'do schłodzenia jajek' },
    ],
    steps: [
      'Wymieszaj sos sojowy, mirin, wodę i cukier w słoiku albo woreczku strunowym.',
      { t: 'Włóż jajka prosto z lodówki do wrzącej wody. Gotuj dokładnie 6 i pół minuty.', timer: 390 },
      { t: 'Od razu przełóż jajka do miski z wodą i lodem na 5 minut.', timer: 300 },
      'Obierz jajka i zanurz je w marynacie tak, żeby były całkiem przykryte.',
      'Marynuj w lodówce od 6 godzin do 2 dni. Im dłużej, tym mocniejszy smak i kolor.',
      'Przekrój na pół tuż przed podaniem. Pasują do ramenu, miski ryżu i sałatek.',
    ],
    tip: 'Czas gotowania zależy od wielkości jajek. Minutnik na stronie głównej policzy go dokładnie, gdy ustawisz żółtko na „Mollet”.',
    link: { href: 'index.html#minutnik', label: 'Ustaw minutnik na jajko mollet' },
    photo: {
      file: 'img/przepisy/jajka-do-ramenu.jpg', w: 960, h: 640, focus: '50% 50%',
      author: 'Guilhem Vellut', license: 'CC BY 2.0', licenseUrl: 'https://creativecommons.org/licenses/by/2.0/',
      source: 'https://commons.wikimedia.org/wiki/File:Egg_@_Chicken_Ramen_@_Yatta_!_Ramen_@_Annecy-le-Vieux_(39824443882).jpg',
    },
  },
  {
    id: 'nalesniki',
    name: 'Naleśniki z serem',
    category: 'desery',
    intro: 'Cienkie naleśniki ze słodkim twarogiem, podsmażone na maśle na złoto.',
    time: 40,
    difficulty: 1,
    servings: 4,
    minServings: 2,
    ingredients: [
      { h: 'Ciasto' },
      { n: 'Mąka pszenna', q: 250, u: 'g' },
      { n: 'Mleko', q: 500, u: 'ml' },
      { n: 'Woda gazowana', q: 150, u: 'ml' },
      { n: 'Jajka', q: 2, u: 'szt.', egg: 'whole' },
      { n: 'Olej', q: 2, u: 'łyżka' },
      { n: 'Sól', q: 1, u: 'szczypta' },
      { h: 'Farsz' },
      { n: 'Twaróg półtłusty', q: 500, u: 'g' },
      { n: 'Żółtko', q: 1, u: 'szt.', egg: 'yolk' },
      { n: 'Cukier', q: 3, u: 'łyżka' },
      { n: 'Ekstrakt waniliowy', q: 1, u: 'łyżeczka' },
      { n: 'Rodzynki', q: 30, u: 'g', opt: true },
      { n: 'Masło', q: 20, u: 'g' },
    ],
    steps: [
      { t: 'Zmiksuj mąkę, mleko, jajka i sól na gładkie ciasto bez grudek. Dodaj olej i wodę gazowaną. Odstaw na 15 minut.', timer: 900 },
      'Rozgrzej patelnię i posmaruj ją cienko olejem. Wlej chochelkę ciasta i rozprowadź je, obracając patelnię.',
      { t: 'Smaż naleśnik około minuty, aż brzegi się zezłocą. Przewróć i smaż jeszcze pół minuty.', timer: 60 },
      'Rozgnieć twaróg widelcem z żółtkiem, cukrem i wanilią. Wmieszaj rodzynki.',
      'Nałóż farsz na naleśniki i zwiń je w rulony albo złóż w koperty.',
      'Przed podaniem podsmaż naleśniki na maśle z obu stron na złoto.',
    ],
    tip: 'Woda gazowana sprawia, że ciasto jest lżejsze, a naleśniki cieńsze i bardziej elastyczne.',
    photo: {
      file: 'img/przepisy/nalesniki.jpg', w: 960, h: 948, focus: '50% 50%',
      author: 'Aw58', license: 'CC BY-SA 4.0', licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
      source: 'https://commons.wikimedia.org/wiki/File:Nale%C5%9Bniki_z_serem_-_13.11.2023.jpg',
    },
  },
  {
    id: 'pavlova',
    name: 'Tort Pavlova',
    category: 'desery',
    intro: 'Beza chrupiąca z wierzchu i ciągnąca w środku, z bitą śmietaną i owocami.',
    time: 30,
    wait: '2 h pieczenia i studzenia',
    difficulty: 2,
    servings: 8,
    minServings: 8,
    step: 4,
    ingredients: [
      { h: 'Beza' },
      { n: 'Białka', q: 4, u: 'szt.', egg: 'white' },
      { n: 'Drobny cukier', q: 200, u: 'g' },
      { n: 'Skrobia ziemniaczana', q: 1, u: 'łyżeczka' },
      { n: 'Ocet winny lub sok z cytryny', q: 1, u: 'łyżeczka' },
      { h: 'Na wierzch' },
      { n: 'Śmietanka 30%', q: 300, u: 'ml' },
      { n: 'Cukier puder', q: 1, u: 'łyżka' },
      { n: 'Truskawki i borówki', q: 300, u: 'g' },
    ],
    steps: [
      'Nagrzej piekarnik do 150 °C. Na papierze do pieczenia narysuj okrąg o średnicy około 20 cm.',
      { t: 'Ubijaj białka na sztywno w czystej, suchej misce. Potem dodawaj po łyżce cukru i ubijaj dalej, aż piana będzie gęsta i lśniąca. Zajmie to około 10 minut.', timer: 600 },
      'Delikatnie wmieszaj skrobię i ocet.',
      'Wyłóż pianę na okrąg i uformuj gniazdo z wgłębieniem na środku.',
      { t: 'Wstaw bezę do piekarnika, zmniejsz temperaturę do 120 °C i piecz 90 minut.', timer: 5400 },
      'Wyłącz piekarnik i zostaw bezę w środku z uchylonymi drzwiczkami, aż całkiem ostygnie.',
      'Tuż przed podaniem ubij śmietankę z cukrem pudrem, wyłóż ją na bezę i udekoruj owocami.',
    ],
    tip: 'Białka nie ubiją się, jeśli trafi do nich choćby kropla żółtka albo tłuszczu. Pozostałe żółtka wykorzystaj do carbonary albo sosu holenderskiego.',
    photo: {
      file: 'img/przepisy/pavlova.jpg', w: 960, h: 760, focus: '50% 50%',
      author: 'Brett Jordan', license: 'CC BY 2.0', licenseUrl: 'https://creativecommons.org/licenses/by/2.0/',
      source: 'https://commons.wikimedia.org/wiki/File:Pavlova_garnished_with_cream_and_strawberries.jpg',
    },
  },
  {
    id: 'tiramisu',
    name: 'Tiramisu',
    category: 'desery',
    intro: 'Biszkopty nasączone kawą przełożone puszystym kremem z mascarpone, żółtek i białek.',
    time: 30,
    wait: '6 h w lodówce',
    difficulty: 2,
    servings: 6,
    minServings: 3,
    ingredients: [
      { n: 'Żółtka', q: 4, u: 'szt.', egg: 'yolk' },
      { n: 'Białka', q: 4, u: 'szt.', egg: 'white' },
      { n: 'Cukier', q: 100, u: 'g' },
      { n: 'Mascarpone', q: 500, u: 'g' },
      { n: 'Biszkopty podłużne', q: 200, u: 'g' },
      { n: 'Mocna kawa, ostudzona', q: 300, u: 'ml' },
      { n: 'Amaretto lub marsala', q: 2, u: 'łyżka', opt: true },
      { n: 'Kakao', q: 2, u: 'łyżka' },
    ],
    steps: [
      { t: 'Ubij żółtka z połową cukru na jasną, puszystą masę, około 5 minut.', timer: 300 },
      'Dodawaj mascarpone po łyżce, miksując na niskich obrotach, aż krem będzie gładki.',
      'W osobnej, czystej misce ubij białka na sztywno z resztą cukru. Wmieszaj je do kremu szpatułką, delikatnie, żeby piana nie opadła.',
      'Wymieszaj kawę z likierem. Maczaj biszkopty w kawie przez sekundę z każdej strony i układaj w naczyniu.',
      'Przykryj biszkopty połową kremu, ułóż drugą warstwę biszkoptów i resztę kremu.',
      'Schowaj do lodówki na co najmniej 6 godzin, najlepiej na noc. Przed podaniem oprósz kakao przez sitko.',
    ],
    tip: 'Jajka w tym deserze są surowe. Używaj najświeższych jajek z pewnego źródła albo jajek pasteryzowanych.',
    link: { href: 'index.html#swiezosc', label: 'Sprawdź, czy Twoje jajka są świeże' },
    photo: {
      file: 'img/przepisy/tiramisu.jpg', w: 960, h: 621, focus: '50% 50%',
      author: 'Sharon Chen', license: 'CC BY 2.0', licenseUrl: 'https://creativecommons.org/licenses/by/2.0/',
      source: 'https://commons.wikimedia.org/wiki/File:Classic_Italian_Tiramisu-3_(29989504485).jpg',
    },
  },
];
